# NixOS Configuration for Golden Image
# Declarative system configuration for Proxmox template

{ config, pkgs, lib, ... }:

{
  imports = [
    # Include the results of the hardware scan
    ./hardware-configuration.nix
  ];

  # Bootloader configuration
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Kernel modules for Proxmox
  boot.initrd.availableKernelModules = [ "virtio_pci" "virtio_scsi" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Filesystem configuration (will be generated by nixos-generate-config)
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # Swap configuration
  swapDevices = [ ];

  # Network configuration
  networking.hostName = "nixos";
  networking.useDHCP = lib.mkDefault true;
  networking.networkmanager.enable = true;

  # Time zone and locale
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  # User configuration
  users.users.root = {
    password = "nixos";  # Temporary - will be managed by cloud-init
    openssh.authorizedKeys.keys = [ ];
  };

  users.mutableUsers = true;

  # System packages
  environment.systemPackages = with pkgs; [
    vim
    curl
    wget
    git
    htop
    neofetch
    cloud-init
    cloud-utils
    qemu_kvm
  ];

  # Services configuration
  services = {
    # OpenSSH
    openssh = {
      enable = true;
      settings = {
        PermitRootLogin = "yes";
        PasswordAuthentication = true;
      };
    };

    # QEMU Guest Agent for Proxmox integration
    qemuGuest.enable = true;

    # Cloud-init for automated configuration
    cloud-init = {
      enable = true;
      network.enable = true;
      ext4.enable = true;
    };
  };

  # Virtualization support
  virtualisation = {
    qemu.guestAgent.enable = true;
  };

  # Enable flakes and nix-command (modern Nix features)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # System state version (don't change after installation)
  system.stateVersion = "24.05";
}
